#!/bin/bash

#######################################
# Display an error message.
# Arguments:
#   String.
# Returns:
#   0
#######################################
err() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

#######################################
# Issues a query
# Arguments:
#   String.
# Returns:
#   Returns
#######################################
query() {
  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
}

echo Hi! I am toolboxmatic, your automatic SingleStore Toolbox configurator!
echo =========================================================================
echo

read -p "Master Aggreator [localhost]: " MASTER
read -p "Master Aggregator Port [3306]: " MA_PORT
read -p "Username [root]: " DB_USER
read -p "Password []:" DB_PASS
read -p "SSH key (enter full path or leave empty for single host deployment) []: " SSH_KEY

if [ -z "${MASTER}" ]; then
    MASTER="localhost"
fi

if [ -z "${MA_PORT}" ]; then
    MA_PORT="3306"
fi

if [ -z "${DB_USER}" ]; then
    DB_USER="root"
fi

# Let's check if the CLI is installed...
CLI=`which singlestore`

if [ -z "${CLI}" ]; then
    CLI=`which memsql`
elif [ -z "${CLI}" ]; then
    CLI=`which mysql`
elif [ -z "${CLI}" ]; then
    err "ERROR: CLI not found. Please install package singlestore-client. For more information visit: https://docs.singlestore.com/db/latest/en/user-and-cluster-administration/cluster-management-with-tools/singlestore-tools-installation/singlestore-client-installation.html"
    exit 1;
fi

# Let's check if toolbox is installed...
CLI=`which sdb-toolbox-config`

if [ -z "${CLI}" ]; then
    err "ERROR: SingleStore Tools are not found. Please install package singlestoredb-toolbox. For more information visit: https://docs.singlestore.com/db/v7.6/en/user-and-cluster-administration/migrate-from-ops-to-tools/sudo/install-singlestore-tools.html"
    exit 1;
fi

err("DEBUG: MA   = ${MASTER}")
err("DEBUG: PORT = ${MA_PORT}")
err("DEBUG: USER = ${DB_USER}")
err("DEBUG: PASS = ${DB_PASS}")
err("DEBUG: SSH  = ${SSH_KEY}")
err("DEBUG: CLI  = ${CLI}")
